CREATE TABLE IF NOT EXISTS sesiones (
  sid VARCHAR(64) PRIMARY KEY,
  id_usuario INTEGER NOT NULL,
  rol VARCHAR(64) NOT NULL,
  expira_en TIMESTAMP NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT NOW()
);
